feat:PostgreSQLAutogeneratedPassword
eclipse-tractusx/sldt-bpn-discovery pull request #71
Opened 2023-11-29 10:36 UTC by shijinrajbosch

## Description

Used the auto-generated PosgtreSQL credentials.

2023-11-30 11:13 UTC, evegufy requested changes

2023-11-30 11:13 UTC, evegufy commented on charts/bpndiscovery/templates/secret.yaml
> +    SPRING_DATASOURCE_PASSWORD: {{ $secretPassword | quote }}
the secret values needs to be the values from [postgres-password](https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/71/files#diff-89698cfe1ba306a56daf2d3119401a86d8b361745a2cb49d7ee0ffd7365d442aR39), not just one 'randAlphaNum 32' like [$secretPassword](https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/71/files#diff-89698cfe1ba306a56daf2d3119401a86d8b361745a2cb49d7ee0ffd7365d442aR22) is currently defined

2023-11-30 11:13 UTC, evegufy commented on charts/bpndiscovery/templates/secret.yaml
> +    password: {{ ( .Values.postgresql.auth.password | b64enc )  | default ( index $secret.data "postgres-password" ) | quote }}
probably copy/paste error: here it's should be 'default $secret.data.password' not 'default ( index $secret.data "postgres-password"'

2023-12-01 10:01 UTC, carslen commented
Re-requested review from @evegufy by accident, sorry.

2023-12-21 12:38 UTC, tunacicek commented
will be done in other PR https://github.com/eclipse-tractusx/sldt-bpn-discovery/pull/74

2023-12-21 12:38 UTC, closed without merging